const DATA = {
  startDate: [2004, 3, 12], // April 12, 2004
  totalMiles: 2040,

  occupations: [
    {
      id: "dealer",
      name: "Dealership Tech",
      money: 1600,
      scoreMult: 1,
      repair: 0.75,
      wisdom: 0.45,
      blurb:
        "You have a Tech 2, a union card, and $1600. You have never crawled under a truck on dirt.",
    },
    {
      id: "shade",
      name: "Shade-Tree Mechanic",
      money: 800,
      scoreMult: 2,
      repair: 1.0,
      wisdom: 0.35,
      blurb:
        "You have a Pittsburgh jack, a milk crate of sockets, and $800. You will not be calling a wrecker.",
    },
    {
      id: "farmer",
      name: "Farmer",
      money: 800,
      scoreMult: 2,
      repair: 0.85,
      wisdom: 0.55,
      extraFood: 200,
      blurb:
        "The truck already earns its keep. You start with extra food and a healthy distrust of orange jack stands.",
    },
    {
      id: "craigslist",
      name: "Craigslist Cowboy",
      money: 400,
      scoreMult: 3,
      repair: 0.45,
      wisdom: 0.2,
      transHit: 22,
      blurb:
        "You bought it last night. Seller said the trans 'might slip in second.' You have $400 and a dream.",
    },
  ],

  trucks: [
    {
      id: "gmt800",
      name: "2003 GMC Sierra 1500",
      spec: "5.3 / 4L60E  ·  the people's truck",
      mpg: 14,
      payload: 1400,
      transMax: 72,
      reliability: 0.62,
      diesel: false,
      fourby: true,
      color: { body: "#1c3f2c", two: "#c5c8c2", roof: "#1c3f2c", stacks: false },
      hero: "assets/trucks/gmt800_hero.jpg",
      sprite: "assets/trucks/gmt800_side.png",
      blurb: "Quiet, handsome, and already negotiating with second gear.",
    },
    {
      id: "square",
      name: "1985 Chevy Silverado C20",
      spec: "350 / TH400  ·  square body",
      mpg: 10,
      payload: 2000,
      transMax: 92,
      reliability: 0.78,
      diesel: false,
      fourby: true,
      color: { body: "#4a2a16", two: "#4a2a16", roof: "#efe6d6", stacks: false },
      hero: "assets/trucks/square_hero.jpg",
      sprite: "assets/trucks/square_side.png",
      blurb: "Rust, a 350, and a prayer. The jack stands remember this one.",
    },
    {
      id: "suburban",
      name: "1987 Chevy Suburban",
      spec: "350 / 700R4  ·  family hauler",
      mpg: 9,
      payload: 1800,
      transMax: 84,
      reliability: 0.7,
      diesel: false,
      fourby: true,
      color: { body: "#2a3d5a", two: "#9aa3ad", roof: "#2a3d5a", stacks: false },
      hero: "assets/trucks/suburban_hero.jpg",
      sprite: "assets/trucks/suburban_side.png",
      blurb: "Nine seats, no crumple zone, and a date with Harbor Freight.",
    },
    {
      id: "c10",
      name: "1978 C10 'Grandpa Hoss'",
      spec: "350 / Turbo 350  ·  the survivor",
      mpg: 11,
      payload: 1200,
      transMax: 96,
      reliability: 0.88,
      diesel: false,
      fourby: false,
      color: { body: "#c4a06a", two: "#5a3a22", roof: "#c4a06a", stacks: false },
      hero: "assets/trucks/c10_hero.jpg",
      sprite: "assets/trucks/c10_side.png",
      blurb: "Turbo 350. Might actually make Oregon. Do not tell the 4L60 guys.",
    },
    {
      id: "lb7",
      name: "2004 Silverado 2500HD",
      spec: "LB7 Duramax / Allison  ·  Truckasaurus-adjacent",
      mpg: 13,
      payload: 2800,
      transMax: 90,
      reliability: 0.58,
      diesel: true,
      fourby: true,
      color: { body: "#1a2420", two: "#d6c6a2", roof: "#1a2420", stacks: true },
      hero: "assets/trucks/lb7_hero.jpg",
      sprite: "assets/trucks/lb7_side.png",
      blurb: "Injectors, HPOP, and a charge pipe that sounds like a shotgun.",
    },
  ],

  stands: [
    {
      id: "harbor",
      name: "Harbor Freight (3-ton, orange)",
      cost: 20,
      fail: 0.22,
      blurb: "They were on sale. They are always on sale.",
    },
    {
      id: "pittsburgh",
      name: "Pittsburgh Heavy Duty",
      cost: 45,
      fail: 0.08,
      blurb: "Still orange-ish. Slightly less of a murder weapon.",
    },
    {
      id: "good",
      name: "Jack stands that aren't orange",
      cost: 90,
      fail: 0.015,
      blurb: "Rated for the truck. A controversial choice on this trail.",
    },
    {
      id: "none",
      name: "Just the floor jack",
      cost: 0,
      fail: 0.4,
      blurb: "You will 'only be under there a second.'",
    },
  ],

  store: [
    { id: "fuel", name: "Fuel (gallons)", price: 2, sell: 1, unit: "gal", weight: 6, max: 55, startHint: 32 },
    { id: "food", name: "Food (lbs)", price: 0.4, sell: 0.3, unit: "lbs", weight: 1, max: 800, startHint: 400 },
    { id: "parts", name: "Spare parts kits", price: 45, sell: 22, unit: "kits", weight: 25, max: 8, startHint: 2 },
    { id: "atf", name: "ATF (quarts)", price: 5, sell: 2, unit: "qts", weight: 2, max: 16, startHint: 4 },
    { id: "ammo", name: "Ammo (boxes)", price: 10, sell: 5, unit: "bx", weight: 3, max: 12, startHint: 4 },
    { id: "beer", name: "Gas-station beer (cases)", price: 12, sell: 7, unit: "cs", weight: 18, max: 8, startHint: 1 },
    { id: "blaster", name: "PB Blaster (cans)", price: 6, sell: 3, unit: "cans", weight: 1, max: 8, startHint: 2 },
  ],

  paces: {
    easy: { label: "Easy (back roads)", miles: 16, wear: 0.55, health: 0.4 },
    steady: { label: "Steady", miles: 28, wear: 1.0, health: 0.85 },
    grinding: { label: "Grinding (hammer down)", miles: 40, wear: 1.85, health: 1.35 },
  },

  rations: {
    starving: { label: "Starving", lbs: 0, health: -8 },
    meager: { label: "Meager", lbs: 1.5, health: -2 },
    filling: { label: "Filling", lbs: 3, health: 1 },
    feast: { label: "Taquito feast", lbs: 5, health: 3 },
  },

  weather: [
    { id: "fair", label: "fair", heat: 0, wet: 0 },
    { id: "hot", label: "hot", heat: 1, wet: 0 },
    { id: "cool", label: "cool", heat: 0, wet: 0 },
    { id: "rain", label: "rain", heat: 0, wet: 1 },
    { id: "storm", label: "a thunderstorm", heat: 0, wet: 2 },
    { id: "cold", label: "cold", heat: -1, wet: 0 },
    { id: "snow", label: "snow", heat: -2, wet: 1 },
    { id: "blizzard", label: "a blizzard", heat: -3, wet: 2 },
  ],

  landmarks: [
    { mile: 0, name: "Independence, MO", kind: "start", talk: "Matt's driveway. The trail starts when the coffee's gone." },
    { mile: 102, name: "Kansas River", kind: "river", depth: [3, 7], talk: "A brown ditch with opinions." },
    { mile: 185, name: "Big Blue River", kind: "river", depth: [2, 6] },
    { mile: 304, name: "Kearney O'Reilly", kind: "shop", talk: "They have a 4L60 in the back. They will not sell it to you." },
    { mile: 554, name: "Chimney Rock", kind: "sight", talk: "It looks like a rusted exhaust stack. The pioneers were truck guys and didn't know it." },
    { mile: 640, name: "Laramie U-Pull-It", kind: "shop", talk: "A cathedral of 14-bolts and mice nests." },
    { mile: 780, name: "Split Rock Sinclair", kind: "shop", talk: "One pump, three dogs, and a coffee pot that's been on since Tuesday." },
    { mile: 830, name: "Independence Rock", kind: "sight", talk: "You carve the VIN into the granite. Tradition." },
    { mile: 932, name: "South Pass", kind: "pass", talk: "The 4L60's last stand. Grade is not a suggestion." },
    { mile: 1005, name: "Farson Fuel", kind: "shop", talk: "The only pump for a hundred miles. They know it." },
    { mile: 1083, name: "Green River", kind: "river", depth: [4, 9] },
    { mile: 1151, name: "Fort Bridger Diesel", kind: "shop", talk: "They look at your gas truck the way a vet looks at a cat." },
    { mile: 1264, name: "Soda Springs Sinclair", kind: "shop", talk: "The taquitos have been under the lamp since Tuesday." },
    { mile: 1395, name: "Fort Hall", kind: "fort", talk: "Idaho. Catalytic converters vanish at dusk." },
    { mile: 1483, name: "Snake River", kind: "river", depth: [5, 10] },
    { mile: 1648, name: "Fort Boise", kind: "fort" },
    { mile: 1740, name: "La Grande Pump", kind: "shop", talk: "Diesel, regular, and a roller grill that has seen things." },
    { mile: 1808, name: "Blue Mountains", kind: "pass", talk: "Clibbins country. Mowers have been here." },
    { mile: 1890, name: "The Clibbins", kind: "clibbins", talk: "Grass clippings on a wet grade. Yew watch yerself, hoss." },
    { mile: 1967, name: "The Dalles", kind: "fort" },
    { mile: 2040, name: "Oregon City Mud Hole", kind: "end", talk: "The end of the trail. Grandpa Hoss is already in the water." },
  ],

  animals: [
    { id: "deer", name: "mule deer", w: 42, h: 36, lbs: 80, speed: 1.4, hp: 1 },
    { id: "turkey", name: "wild turkey", w: 28, h: 22, lbs: 12, speed: 2.2, hp: 1 },
    { id: "coyote", name: "coyote", w: 34, h: 20, lbs: 18, speed: 2.0, hp: 1 },
    { id: "cow", name: "feral cow", w: 64, h: 40, lbs: 180, speed: 0.7, hp: 2 },
    { id: "squirrel", name: "squirrel", w: 14, h: 10, lbs: 2, speed: 2.8, hp: 1 },
  ],

  talk: [
    "GOBBLESS HOSS. Watch them clibbins on the Barlow.",
    "Don't cheap out on jack stands. I knew a fella named Devin.",
    "That 4L60'll make it. Probably. Shift like you're apologizing.",
    "Harbor Freight is a lifestyle, not a store.",
    "You can smell a rebuilt trans from Facebook. It smells like hope and metal.",
    "If the charge pipe goes, you will not know if the engine exploded or if someone fired a shotgun.",
    "Pittsburgh stands are Harbor Freight stands that went to community college.",
    "Never crawl under a truck with just the jack. I mean it. I am an educational software title.",
    "South Pass is where GMT-800s go to become two trucks.",
    "A man in a cowboy hat is selling a 'good used Allison' out of a horse trailer.",
    "The square body will outlive you. That is not a compliment.",
    "Taquitos are a food group if you believe hard enough.",
    "If she slips in second, she is talking to you. Listen.",
    "I forded this creek in a C10 in '78. The C10 is still in the creek.",
    "Orange means danger. Also means sale. These two facts are related.",
  ],

  deaths: {
    "4l60": {
      image: "assets/deaths/4l60.jpg",
      baked: true,
      cause: "a 4L60",
      epitaph: "split in half trying to shift into second",
      line: "You died because your 4L60 split in half trying to shift into second gear.",
    },
    jackstands: {
      image: "assets/deaths/jackstands.jpg",
      baked: true,
      cause: "Harbor Freight jack stands",
      epitaph: "trusted the orange ones",
      line: "You have been killed by Harbor Freight jack stands.",
    },
    suburban: {
      image: "assets/deaths/suburban.jpg",
      baked: false,
      cause: "a jack stand failure",
      epitaph: "the Suburban remembered gravity",
      line: "While working under the truck, the jack stands failed. The vehicle fell. You did not survive.",
    },
    truckasaurus: {
      image: "assets/deaths/truckasaurus.jpg",
      baked: true,
      cause: "a heart attack",
      epitaph: "thought the engine was a shotgun",
      line: "The charge air pipe let go. You could not tell if the engine exploded or if someone fired a shotgun. You have died of a heart attack.",
    },
    clibbins: {
      image: "assets/deaths/clibbins.jpg",
      baked: true,
      cause: "them clibbins",
      epitaph: "slipped awn dem clibbins",
      line: "YEW SLIPD AWN DEM CLIBBINS HOSS",
    },
    floorjack: {
      image: "assets/deaths/floorjack.jpg",
      baked: false,
      cause: "a floor jack on dirt",
      epitaph: "it was only gonna be a second",
      line: "The floor jack kicked out in the dirt. The truck came down. You have died under your own rig.",
    },
    battery: {
      image: "assets/deaths/battery.jpg",
      baked: false,
      cause: "a battery explosion",
      epitaph: "jumped it off backwards",
      line: "The battery exploded while you were jump-starting. Acid, sparks, and a lesson about polarity.",
    },
    dysentery: {
      image: null,
      baked: false,
      cause: "taquito dysentery",
      epitaph: "trusted the roller grill",
      line: "You have died of dysentery. The Sinclair taquito is listed as the weapon.",
    },
    atf: {
      image: null,
      baked: false,
      cause: "ATF poisoning",
      epitaph: "thought it was Gatorade",
      line: "You drank Dexron III out of a Gatorade bottle. You have died of ATF poisoning.",
    },
    impact: {
      image: null,
      baked: false,
      cause: "an impact wrench",
      epitaph: "one more click",
      line: "The impact broke a rusty bolt, then your wrist, then your will. Infection set in. You have died.",
    },
    radiator: {
      image: null,
      baked: false,
      cause: "a radiator",
      epitaph: "opened the cap hot",
      line: "You opened the radiator cap while it was hot. You have died of scalding.",
    },
    exhaust: {
      image: null,
      baked: false,
      cause: "carbon monoxide",
      epitaph: "slept in the cab with a leak",
      line: "You slept in the cab with an exhaust leak. You did not wake up.",
    },
    drowning: {
      image: "assets/bg/river.jpg",
      baked: false,
      cause: "drowning",
      epitaph: "tried to ford it",
      line: "The truck took a swim. You went with it. You have drowned.",
    },
    winter: {
      image: null,
      baked: false,
      cause: "the cold",
      epitaph: "heater core was already gone",
      line: "The heater core had been bypassed since Nebraska. You have died of the cold.",
    },
    starvation: {
      image: null,
      baked: false,
      cause: "starvation",
      epitaph: "out of taquitos",
      line: "The food ran out. The beer ran out. You have died of starvation.",
    },
    stranded: {
      image: null,
      baked: false,
      cause: "being stranded",
      epitaph: "out of fuel and friends",
      line: "No fuel, no parts, no one coming. You have died on the shoulder.",
    },
    tire: {
      image: null,
      baked: false,
      cause: "a tire explosion",
      epitaph: "aired it up with the pancake compressor",
      line: "The rusted wheel exploded while you were airing it up. You have died.",
    },
  },

  npcTrades: [
    { give: { food: 50 }, take: { ammo: 1 }, line: "A hunter wants 50 lbs of food for a box of shells." },
    { give: { parts: 1 }, take: { fuel: 12 }, line: "A wrecker driver will trade 12 gallons of fuel for a parts kit." },
    { give: { beer: 1 }, take: { atf: 4 }, line: "A man in a vest wants a case of beer for 4 quarts of ATF. This is a fair trade in America." },
    { give: { ammo: 2 }, take: { food: 80 }, line: "A farm kid will trade 80 lbs of venison for 2 boxes of ammo." },
    { give: { blaster: 1 }, take: { parts: 1 }, line: "A shade-tree at a rest stop will trade a parts kit for a can of PB Blaster." },
    { give: { food: 80 }, take: { money: 40 }, line: "A diner will buy 80 lbs of meat off you for $40." },
    { give: { beer: 1 }, take: { money: 10 }, line: "A cowboy will pay $10 cash for a cold case." },
    { give: { parts: 1 }, take: { money: 28 }, line: "A shop will take a parts kit for $28 and not ask where it came from." },
    { give: { fuel: 10 }, take: { money: 15 }, line: "A stranded Civic will buy 10 gallons off you for $15." },
  ],

  jobs: [
    {
      id: "flat_lady",
      text: "An old woman in a Buick Century has a flat on the shoulder. She holds out two twenties and a pie tin of cookies.",
      pay: 40,
      fuelPay: 3,
      ok: "You change the tire. She calls you a gentleman and tops off a can. +$40 and 3 gal.",
    },
    {
      id: "jump_van",
      text: "A minivan is dead in a rest-area stall. A dad offers $25 for a jump and swears he knows the polarity.",
      pay: 25,
      batteryRisk: 0.07,
      ok: "It fires. He tries to tip you in fruit snacks. You take the $25.",
    },
    {
      id: "ditch",
      text: "A Civic is in the ditch, proud and stuck. They'll pay $70 if you snatch them out.",
      pay: 70,
      fuel: 2,
      ok: "You snatch it out. The Civic smells like vape. +$70.",
    },
    {
      id: "under_ram",
      text: "A lifted Ram is leaking on jack stands that look familiar. $90 to crawl under and tighten a fitting.",
      pay: 90,
      under: true,
      ok: "You tighten it. You live. +$90.",
    },
    {
      id: "wrecker",
      text: "A wrecker driver needs a second set of hands for an overnight recovery. $120, and you lose a day.",
      pay: 120,
      days: 1,
      ok: "You winch a Tahoe off a culvert at 2 a.m. +$120.",
    },
    {
      id: "tractor",
      text: "A farmer's tractor won't start. He offers $50 and a cooler of venison if you can make it cough.",
      pay: 50,
      food: 40,
      ok: "You clean the solenoid. He loads the cooler. +$50 and 40 lbs food.",
    },
    {
      id: "parts_run",
      text: "A shop in the next town will pay $55 if you run a water pump over before they close.",
      pay: 55,
      fuelPay: 5,
      ok: "You make it with ten minutes to spare. They throw in 5 gallons. +$55.",
    },
    {
      id: "boat_ramp",
      text: "A man has a boat trailer high-centered on a ramp. $80 to pull him off before the lake takes the F-150.",
      pay: 80,
      fuel: 3,
      ok: "You snatch the trailer. He cries a little. +$80.",
    },
    {
      id: "oil_change",
      text: "A kid in a parking lot bought Harbor Freight stands and a 5.3. He'll pay $45 if you'll show him how an oil change works.",
      pay: 45,
      under: true,
      ok: "You do the oil. You lecture him about the stands. +$45.",
    },
    {
      id: "hay",
      text: "A ranch wants a pickup bed of hay moved two miles. $35 and they don't care about your payload sticker.",
      pay: 35,
      ok: "You stack hay. Your trans notices. +$35.",
    },
  ],
};
